-- ============================================================
-- Closette AI — initial schema (V1)
-- UUID PKs are generated by the application; timestamps are UTC.
-- List-typed columns (colors/styles/seasons/ingredients/item_ids) are stored
-- comma-separated via StringListConverter.
-- ============================================================

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(80),
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE style_preferences (
    id                    UUID PRIMARY KEY,
    user_id               UUID NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    favorite_colors       VARCHAR(1000),
    preferred_styles      VARCHAR(1000),
    onboarding_completed  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ NOT NULL
);

CREATE TABLE wardrobe_items (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    category    VARCHAR(32) NOT NULL,
    subcategory VARCHAR(255),
    colors      VARCHAR(500),
    pattern     VARCHAR(255),
    styles      VARCHAR(500),
    seasons     VARCHAR(200),
    brand       VARCHAR(255),
    size        VARCHAR(64),
    image_key   VARCHAR(512),
    favorite    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_wardrobe_user ON wardrobe_items (user_id);
CREATE INDEX idx_wardrobe_user_category ON wardrobe_items (user_id, category);

CREATE TABLE beauty_items (
    id               UUID PRIMARY KEY,
    user_id          UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    brand            VARCHAR(255),
    product_name     VARCHAR(255) NOT NULL,
    category         VARCHAR(32) NOT NULL,
    image_key        VARCHAR(512),
    size             VARCHAR(64),
    ingredients      VARCHAR(4000),
    purchase_date    DATE,
    opened_date      DATE,
    expiry_date      DATE,
    pao_months       INTEGER,
    amount_remaining INTEGER,
    favorite         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_beauty_user ON beauty_items (user_id);
CREATE INDEX idx_beauty_user_category ON beauty_items (user_id, category);

CREATE TABLE wishlist_items (
    id           UUID PRIMARY KEY,
    user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_name VARCHAR(255) NOT NULL,
    brand        VARCHAR(255),
    price        NUMERIC(12, 2),
    category     VARCHAR(64),
    image_key    VARCHAR(512),
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_wishlist_user ON wishlist_items (user_id);

CREATE TABLE outfits (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      VARCHAR(255),
    occasion   VARCHAR(255),
    item_ids   VARCHAR(2000),
    status     VARCHAR(16) NOT NULL,
    favorite   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_outfits_user ON outfits (user_id);

CREATE TABLE outfit_feedback (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    outfit_id  UUID,
    signal     VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_feedback_user ON outfit_feedback (user_id);

CREATE TABLE preference_weights (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    attribute  VARCHAR(128) NOT NULL,
    weight     DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_pref_user_attr UNIQUE (user_id, attribute)
);
CREATE INDEX idx_pref_user ON preference_weights (user_id);
